// <auto-generated />
using System;
using CCRestitution.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCRestitution.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CCRestitution.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<int>("AgencyCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CaseNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ClosedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustodyStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Docket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JudgeId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountId");

                    b.HasIndex("CourtId");

                    b.HasIndex("JudgeId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CCRestitution.Models.Court", b =>
                {
                    b.Property<int>("CourtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourtId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourtId");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("CCRestitution.Models.Crime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AO_Indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Armed_VFO_Charge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attempted_CCI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attempted_Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attempted_DNA_Indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attempted_NYS_Law_Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attempted_VF_Indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Auto_Strip_Charge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bus_Driver_Charge_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Career_Criminal_Charge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Civil_Confinement_Indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DMV_VTCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNA_Indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_Invalidated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EFFECTIVE_DATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Escape_Charge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expanded_Law_Literal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FP_Offense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Law_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hate_Crime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBR_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INS_Charge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JD_Indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JO_Indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jail_Charge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Law_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Law_Ordinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MCDV_Charge_Indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MODIFIED_DATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maxi_Law_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mini_Law_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Minors_Charge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NCIC_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NYS_Law_Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Non_Seal_Charge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Offense_Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Post_Convict_Charge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RDLR_Indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REPEAL_DATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RTA_FP_Offense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAFIS_Crime_Cateory_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex_Offender_Registry_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexually_Motivated_Ind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sub_Convict_Charge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sub_Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sub_Section13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terrorism_Indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UCR_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unconst_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("VF_Indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weapon_Charge")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Crimes");
                });

            modelBuilder.Entity("CCRestitution.Models.Defendant", b =>
                {
                    b.Property<int>("DefendantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DefendantId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suffix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DefendantId");

                    b.HasIndex("AccountId");

                    b.ToTable("Defendants");
                });

            modelBuilder.Entity("CCRestitution.Models.Judge", b =>
                {
                    b.Property<int>("JudgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JudgeId"));

                    b.Property<int?>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("JudgeId");

                    b.HasIndex("CourtId");

                    b.ToTable("Judges");
                });

            modelBuilder.Entity("CCRestitution.Models.MoneyOrdered", b =>
                {
                    b.Property<int>("MoneyOrderedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoneyOrderedId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Closed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EHM")
                        .HasColumnType("bit");

                    b.Property<decimal?>("EHMAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("FineCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FineOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinePayByDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MandatorySurchargeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("MandatorySurchargeCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MandatorySurchargeOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MandatorySurchargePayByDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Opened")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OtherAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("OtherCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OtherOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OtherPayByDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("RestitutionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RestitutionCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RestitutionOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RestitutionPayByDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SupervisionFeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SupervisionFeeCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SupervisionFeeOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SurchargeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SurchargeCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SurchargeOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SurchargePayByDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("YO")
                        .HasColumnType("bit");

                    b.HasKey("MoneyOrderedId");

                    b.ToTable("MoneyOrdered");
                });

            modelBuilder.Entity("CCRestitution.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int?>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EHMAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MandatorySurchargeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OtherAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RestitutionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SupervisionFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SurchargeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CCRestitution.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CCRestitution.Models.Victim", b =>
                {
                    b.Property<int>("VictimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VictimId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AmountDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CaseNumber")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VictimId");

                    b.HasIndex("AccountId");

                    b.ToTable("Victims");
                });

            modelBuilder.Entity("CCRestitution.Models.Account", b =>
                {
                    b.HasOne("CCRestitution.Models.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCRestitution.Models.Judge", "Judge")
                        .WithMany()
                        .HasForeignKey("JudgeId");

                    b.Navigation("Court");

                    b.Navigation("Judge");
                });

            modelBuilder.Entity("CCRestitution.Models.Crime", b =>
                {
                    b.HasOne("CCRestitution.Models.Account", null)
                        .WithMany("Crimes")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("CCRestitution.Models.Defendant", b =>
                {
                    b.HasOne("CCRestitution.Models.Account", null)
                        .WithMany("Defendants")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("CCRestitution.Models.Judge", b =>
                {
                    b.HasOne("CCRestitution.Models.Court", "Court")
                        .WithMany("Judges")
                        .HasForeignKey("CourtId");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("CCRestitution.Models.Victim", b =>
                {
                    b.HasOne("CCRestitution.Models.Account", null)
                        .WithMany("Victims")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("CCRestitution.Models.Account", b =>
                {
                    b.Navigation("Crimes");

                    b.Navigation("Defendants");

                    b.Navigation("Victims");
                });

            modelBuilder.Entity("CCRestitution.Models.Court", b =>
                {
                    b.Navigation("Judges");
                });
#pragma warning restore 612, 618
        }
    }
}
