using CCRestitution.PdfImplementation.DocumentModels;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Drawing.Printing;

namespace CCRestitution.PdfImplementation.Templates
{
    public class BaseReportTemplate : IDocument
    {
        public ReportDataModel Model { get; }

        public BaseReportTemplate(ReportDataModel model)
        {
            Model = model;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;
        public DocumentSettings GetSettings() => DocumentSettings.Default;


        public virtual void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Margin(Model.Margin, Model.MarginUnit);
                if(Model.Orientation == ReportOrientation.Landscape)
                {
                    page.Size(PageSizes.Letter.Landscape());
                }
                else
                {
                    page.Size(PageSizes.Letter.Portrait());
                }
                page.Header().Element(ComposeHeader);
                page.Content().Element(ComposeContent);
                page.Footer().Element(ComposeFooter);
            });
        }

        public virtual void ComposeContent(IContainer container)
        {
            container.PaddingVertical(40).Placeholder();
        }

        public virtual void ComposeHeader(IContainer container)
        {
            var titleStyle = TextStyle.Default.FontSize(20).SemiBold().FontColor(Colors.Blue.Darken3);

            container.ShowOnce().Row(row =>
            {
                row.RelativeItem().AlignCenter().Column(column =>
                {
                    column.Item().AlignCenter().Text(Model.Title).Style(titleStyle);

                    if (Model.DisplayDateAsSpan)
                    {
                        column.Item().AlignCenter().Text($"{Model.StartDate.ToString(Model.DateFormat)} - {Model.EndDate.ToString(Model.DateFormat)}");
                    }
                    else
                    {
                        column.Item().AlignCenter().Text(Model.StartDate.ToString(Model.DateFormat));
                    }

                });
            });
        }

        public virtual void ComposeFooter(IContainer container)
        {
            container.Row(row =>
            {
                row.RelativeItem().Column(column =>
                {
                    column.Item().AlignBottom().Text(text =>
                    {
                        text.Span("Generated On: ");
                        text.Span(Model.GeneratedDate.ToString(Model.GeneratedDateFormat)).Italic();
                    });
                    if (!String.IsNullOrEmpty(Model.UserName))
                    {
                        column.Item().Text(text =>
                        {
                            text.Span("Generated By: ");
                            text.Span(Model.UserName).Italic();
                        });
                    }
                });

                row.AutoItem().AlignRight().AlignBottom().Text(text =>
                {
                    text.CurrentPageNumber();
                    text.Span(" / ");
                    text.TotalPages();
                });
            });
        }
    }
}
